### ISSUE TITLE
Cocoapods Trunk is 1.1.0 but master is 1.2.0

### ISSUE THREAD

**Issue by mbalex99** [MihaelIsaev/RxCodyFire#1]
Cocoapods Trunk is 1.1.0 but master is 1.2.0

Any plans to push master to the Cocoapods trunk?

Right now I'm doing

```ruby
pod 'RxCodyFire', :git => 'https://github.com/MihaelIsaev/RxCodyFire', :commit => '0890678'
```

**Comment by MihaelIsaev** [comment]
![Снимок экрана 2019-03-11 в 2 41 23](https://user-images.githubusercontent.com/1272610/54092580-2a500f00-43a7-11e9-9d86-560434efef02.jpg)
Fixed! Thank you 🙂
